export const animalData = [
  { id: 1, animalName: 'Wambenger, red-tailed', coolFactor: 58 },
  { id: 2, animalName: 'Phalarope, red-necked', coolFactor: 17 },
  { id: 3, animalName: 'Spotted deer', coolFactor: 67 },
  { id: 4, animalName: 'Defassa waterbuck', coolFactor: 96 },
  { id: 5, animalName: 'Pied cormorant', coolFactor: 68 },
  { id: 6, animalName: 'Common goldeneye', coolFactor: 60 },
  { id: 7, animalName: "Squirrel, smith's bush", coolFactor: 10 },
  { id: 8, animalName: 'Raccoon, crab-eating', coolFactor: 37 },
  { id: 9, animalName: 'Raccoon, common', coolFactor: 25 },
  { id: 10, animalName: 'Ringtail, common', coolFactor: 87 },
  { id: 11, animalName: 'Dolphin, bottle-nose', coolFactor: 11 },
  { id: 12, animalName: 'Monster, gila', coolFactor: 92 },
  { id: 13, animalName: 'Common raccoon', coolFactor: 10 },
  { id: 14, animalName: 'Red-cheeked cordon bleu', coolFactor: 23 },
  { id: 15, animalName: 'Black-throated cardinal', coolFactor: 86 },
  { id: 16, animalName: 'Palm squirrel', coolFactor: 6 },
  { id: 17, animalName: 'North American river otter', coolFactor: 31 },
  { id: 18, animalName: 'Black-winged stilt', coolFactor: 4 },
  { id: 19, animalName: 'Water moccasin', coolFactor: 35 },
  { id: 20, animalName: 'Kite, black', coolFactor: 54 },
  { id: 21, animalName: 'Arctic tern', coolFactor: 15 },
  { id: 22, animalName: 'Zorilla', coolFactor: 41 },
  { id: 23, animalName: 'Blue crane', coolFactor: 40 },
  { id: 24, animalName: 'Lizard, giant girdled', coolFactor: 14 },
  { id: 25, animalName: "Sloth, hoffman's", coolFactor: 93 },
  { id: 26, animalName: 'Chilean flamingo', coolFactor: 17 },
  { id: 27, animalName: 'Badger, european', coolFactor: 58 },
  { id: 28, animalName: 'Crane, brolga', coolFactor: 39 },
  { id: 29, animalName: 'Starling, superb', coolFactor: 91 },
  { id: 30, animalName: 'Beaver, north american', coolFactor: 55 },
  { id: 31, animalName: 'White-fronted bee-eater', coolFactor: 56 },
  { id: 32, animalName: 'North American river otter', coolFactor: 18 },
  { id: 33, animalName: 'Water moccasin', coolFactor: 1 },
  { id: 34, animalName: 'Eagle, long-crested hawk', coolFactor: 14 },
  { id: 35, animalName: 'Jackal, golden', coolFactor: 68 },
  { id: 36, animalName: 'Grouse, greater sage', coolFactor: 73 },
  { id: 37, animalName: 'Cockatoo, sulfur-crested', coolFactor: 32 },
  { id: 38, animalName: 'Yellow-crowned night heron', coolFactor: 54 },
  { id: 39, animalName: 'Manatee', coolFactor: 16 },
  { id: 40, animalName: 'Red kangaroo', coolFactor: 14 },
  { id: 41, animalName: 'Snake, eastern indigo', coolFactor: 71 },
  { id: 42, animalName: 'Red-billed tropic bird', coolFactor: 14 },
  { id: 43, animalName: 'Field flicker', coolFactor: 31 },
  { id: 44, animalName: 'Osprey', coolFactor: 82 },
  { id: 45, animalName: 'Pine squirrel', coolFactor: 49 },
  { id: 46, animalName: 'Rhea, greater', coolFactor: 98 },
  { id: 47, animalName: 'Little grebe', coolFactor: 71 },
  { id: 48, animalName: 'Burrowing owl', coolFactor: 53 },
  { id: 49, animalName: 'American badger', coolFactor: 29 },
  { id: 50, animalName: 'Violet-eared waxbill', coolFactor: 72 },
  { id: 51, animalName: "Leadbeateri's ground hornbill", coolFactor: 9 },
  { id: 52, animalName: 'Kite, black', coolFactor: 56 },
  { id: 53, animalName: 'Lion, asian', coolFactor: 39 },
  { id: 54, animalName: 'Crested screamer', coolFactor: 76 },
  { id: 55, animalName: 'Vulture, turkey', coolFactor: 10 },
  { id: 56, animalName: 'Badger, eurasian', coolFactor: 62 },
  { id: 57, animalName: 'Blue-footed booby', coolFactor: 89 },
  { id: 58, animalName: 'Greater sage grouse', coolFactor: 94 },
  { id: 59, animalName: 'Mongoose, banded', coolFactor: 27 },
  { id: 60, animalName: 'Collared lemming', coolFactor: 88 },
  { id: 61, animalName: 'Stanley bustard', coolFactor: 97 },
  { id: 62, animalName: 'White stork', coolFactor: 1 },
  { id: 63, animalName: 'Long-finned pilot whale', coolFactor: 44 },
  { id: 64, animalName: 'Indian star tortoise', coolFactor: 4 },
  { id: 65, animalName: 'Wapiti, elk,', coolFactor: 81 },
  { id: 66, animalName: 'Butterfly (unidentified)', coolFactor: 3 },
  { id: 67, animalName: 'Black-winged stilt', coolFactor: 12 },
  { id: 68, animalName: 'Blue catfish', coolFactor: 46 },
  { id: 69, animalName: 'Black-fronted bulbul', coolFactor: 79 },
  { id: 70, animalName: 'Hawk-eagle, crowned', coolFactor: 17 },
  { id: 71, animalName: 'Komodo dragon', coolFactor: 56 },
  { id: 72, animalName: 'Turtle, snake-necked', coolFactor: 52 },
  { id: 73, animalName: 'Ibis, glossy', coolFactor: 29 },
  { id: 74, animalName: 'Long-billed cockatoo', coolFactor: 69 },
  { id: 75, animalName: "Steller's sea lion", coolFactor: 95 },
  { id: 76, animalName: 'Red kangaroo', coolFactor: 38 },
  { id: 77, animalName: 'Pronghorn', coolFactor: 48 },
  { id: 78, animalName: 'Bear, polar', coolFactor: 84 },
  { id: 79, animalName: 'European stork', coolFactor: 12 },
  { id: 80, animalName: 'Zorilla', coolFactor: 19 },
  { id: 81, animalName: 'Bat, madagascar fruit', coolFactor: 68 },
  { id: 82, animalName: 'Lemming, arctic', coolFactor: 79 },
  { id: 83, animalName: 'Netted rock dragon', coolFactor: 62 },
  { id: 84, animalName: 'Springbuck', coolFactor: 66 },
  { id: 85, animalName: 'Grey-footed squirrel', coolFactor: 30 },
  { id: 86, animalName: 'Otter, brazilian', coolFactor: 61 },
  { id: 87, animalName: 'Four-striped grass mouse', coolFactor: 36 },
  { id: 88, animalName: 'Roan antelope', coolFactor: 68 },
  { id: 89, animalName: "Gazelle, grant's", coolFactor: 55 },
  { id: 90, animalName: 'Dove, rock', coolFactor: 76 },
  { id: 91, animalName: 'Malay squirrel (unidentified)', coolFactor: 69 },
  { id: 92, animalName: 'Steenbok', coolFactor: 35 },
  { id: 93, animalName: 'Dog, raccoon', coolFactor: 30 },
  { id: 94, animalName: 'Bent-toed gecko', coolFactor: 12 },
  { id: 95, animalName: 'White-lipped peccary', coolFactor: 18 },
  { id: 96, animalName: 'Mexican wolf', coolFactor: 97 },
  { id: 97, animalName: 'Long-nosed bandicoot', coolFactor: 35 },
  { id: 98, animalName: 'Galapagos dove', coolFactor: 15 },
  { id: 99, animalName: 'Dove, galapagos', coolFactor: 62 },
  { id: 100, animalName: 'Violet-crested turaco', coolFactor: 40 },
];
